//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package spec

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessProfile) DeepCopyInto(out *AccessProfile) {
	*out = *in
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = new(ToolsAccess)
		(*in).DeepCopyInto(*out)
	}
	if in.Egress != nil {
		in, out := &in.Egress, &out.Egress
		*out = new(EgressAccess)
		(*in).DeepCopyInto(*out)
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(NetworkAccess)
		(*in).DeepCopyInto(*out)
	}
	if in.GitHub != nil {
		in, out := &in.GitHub, &out.GitHub
		*out = new(GitHubAccess)
		(*in).DeepCopyInto(*out)
	}
	if in.Browser != nil {
		in, out := &in.Browser, &out.Browser
		*out = new(BrowserAccess)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessProfile.
func (in *AccessProfile) DeepCopy() *AccessProfile {
	if in == nil {
		return nil
	}
	out := new(AccessProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrowserAccess) DeepCopyInto(out *BrowserAccess) {
	*out = *in
	if in.Session != nil {
		in, out := &in.Session, &out.Session
		*out = new(BrowserSession)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrowserAccess.
func (in *BrowserAccess) DeepCopy() *BrowserAccess {
	if in == nil {
		return nil
	}
	out := new(BrowserAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrowserSession) DeepCopyInto(out *BrowserSession) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrowserSession.
func (in *BrowserSession) DeepCopy() *BrowserSession {
	if in == nil {
		return nil
	}
	out := new(BrowserSession)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChannelBinding) DeepCopyInto(out *ChannelBinding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChannelBinding.
func (in *ChannelBinding) DeepCopy() *ChannelBinding {
	if in == nil {
		return nil
	}
	out := new(ChannelBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Connection) DeepCopyInto(out *Connection) {
	*out = *in
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(ModelEndpoint)
		(*in).DeepCopyInto(*out)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Connection.
func (in *Connection) DeepCopy() *Connection {
	if in == nil {
		return nil
	}
	out := new(Connection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressAccess) DeepCopyInto(out *EgressAccess) {
	*out = *in
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressAccess.
func (in *EgressAccess) DeepCopy() *EgressAccess {
	if in == nil {
		return nil
	}
	out := new(EgressAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionProfile) DeepCopyInto(out *ExecutionProfile) {
	*out = *in
	if in.RequiredFeatures != nil {
		in, out := &in.RequiredFeatures, &out.RequiredFeatures
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionProfile.
func (in *ExecutionProfile) DeepCopy() *ExecutionProfile {
	if in == nil {
		return nil
	}
	out := new(ExecutionProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubAccess) DeepCopyInto(out *GitHubAccess) {
	*out = *in
	if in.Repos != nil {
		in, out := &in.Repos, &out.Repos
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubAccess.
func (in *GitHubAccess) DeepCopy() *GitHubAccess {
	if in == nil {
		return nil
	}
	out := new(GitHubAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Grant) DeepCopyInto(out *Grant) {
	*out = *in
	if in.Operations != nil {
		in, out := &in.Operations, &out.Operations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Grant.
func (in *Grant) DeepCopy() *Grant {
	if in == nil {
		return nil
	}
	out := new(Grant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessProfile) DeepCopyInto(out *HarnessProfile) {
	*out = *in
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(ModelSelection)
		(*in).DeepCopyInto(*out)
	}
	if in.RequiredCapabilities != nil {
		in, out := &in.RequiredCapabilities, &out.RequiredCapabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessProfile.
func (in *HarnessProfile) DeepCopy() *HarnessProfile {
	if in == nil {
		return nil
	}
	out := new(HarnessProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryStore) DeepCopyInto(out *MemoryStore) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryStore.
func (in *MemoryStore) DeepCopy() *MemoryStore {
	if in == nil {
		return nil
	}
	out := new(MemoryStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessageRoute) DeepCopyInto(out *MessageRoute) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessageRoute.
func (in *MessageRoute) DeepCopy() *MessageRoute {
	if in == nil {
		return nil
	}
	out := new(MessageRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelEndpoint) DeepCopyInto(out *ModelEndpoint) {
	*out = *in
	if in.APIs != nil {
		in, out := &in.APIs, &out.APIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]ModelEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelEndpoint.
func (in *ModelEndpoint) DeepCopy() *ModelEndpoint {
	if in == nil {
		return nil
	}
	out := new(ModelEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelEntry) DeepCopyInto(out *ModelEntry) {
	*out = *in
	if in.APIs != nil {
		in, out := &in.APIs, &out.APIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelEntry.
func (in *ModelEntry) DeepCopy() *ModelEntry {
	if in == nil {
		return nil
	}
	out := new(ModelEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelSelection) DeepCopyInto(out *ModelSelection) {
	*out = *in
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelSelection.
func (in *ModelSelection) DeepCopy() *ModelSelection {
	if in == nil {
		return nil
	}
	out := new(ModelSelection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkAccess) DeepCopyInto(out *NetworkAccess) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]NetworkRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkAccess.
func (in *NetworkAccess) DeepCopy() *NetworkAccess {
	if in == nil {
		return nil
	}
	out := new(NetworkAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkRule) DeepCopyInto(out *NetworkRule) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkRule.
func (in *NetworkRule) DeepCopy() *NetworkRule {
	if in == nil {
		return nil
	}
	out := new(NetworkRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationSpec) DeepCopyInto(out *OrganizationSpec) {
	*out = *in
	if in.CultureRefs != nil {
		in, out := &in.CultureRefs, &out.CultureRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TeamTemplates != nil {
		in, out := &in.TeamTemplates, &out.TeamTemplates
		*out = make(map[string]TeamTemplate, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Teams != nil {
		in, out := &in.Teams, &out.Teams
		*out = make(map[string]Team, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.MemoryStores != nil {
		in, out := &in.MemoryStores, &out.MemoryStores
		*out = make(map[string]MemoryStore, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SharedWorkspaces != nil {
		in, out := &in.SharedWorkspaces, &out.SharedWorkspaces
		*out = make(map[string]SharedWorkspace, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.HarnessProfiles != nil {
		in, out := &in.HarnessProfiles, &out.HarnessProfiles
		*out = make(map[string]HarnessProfile, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.ExecutionProfiles != nil {
		in, out := &in.ExecutionProfiles, &out.ExecutionProfiles
		*out = make(map[string]ExecutionProfile, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.SandboxProfiles != nil {
		in, out := &in.SandboxProfiles, &out.SandboxProfiles
		*out = make(map[string]SandboxProfile, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.AccessProfiles != nil {
		in, out := &in.AccessProfiles, &out.AccessProfiles
		*out = make(map[string]AccessProfile, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Connections != nil {
		in, out := &in.Connections, &out.Connections
		*out = make(map[string]Connection, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Seats != nil {
		in, out := &in.Seats, &out.Seats
		*out = make(map[string]Seat, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Grants != nil {
		in, out := &in.Grants, &out.Grants
		*out = make(map[string]Grant, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.MessageRoutes != nil {
		in, out := &in.MessageRoutes, &out.MessageRoutes
		*out = make(map[string]MessageRoute, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ChannelBindings != nil {
		in, out := &in.ChannelBindings, &out.ChannelBindings
		*out = make(map[string]ChannelBinding, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.WorkPublication != nil {
		in, out := &in.WorkPublication, &out.WorkPublication
		*out = new(WorkPublication)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationSpec.
func (in *OrganizationSpec) DeepCopy() *OrganizationSpec {
	if in == nil {
		return nil
	}
	out := new(OrganizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxProfile) DeepCopyInto(out *SandboxProfile) {
	*out = *in
	if in.RequiredEnforcement != nil {
		in, out := &in.RequiredEnforcement, &out.RequiredEnforcement
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxProfile.
func (in *SandboxProfile) DeepCopy() *SandboxProfile {
	if in == nil {
		return nil
	}
	out := new(SandboxProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Seat) DeepCopyInto(out *Seat) {
	*out = *in
	if in.Teams != nil {
		in, out := &in.Teams, &out.Teams
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Workspace != nil {
		in, out := &in.Workspace, &out.Workspace
		*out = new(WorkspaceBinding)
		(*in).DeepCopyInto(*out)
	}
	if in.InstructionRefs != nil {
		in, out := &in.InstructionRefs, &out.InstructionRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AccessProfiles != nil {
		in, out := &in.AccessProfiles, &out.AccessProfiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Seat.
func (in *Seat) DeepCopy() *Seat {
	if in == nil {
		return nil
	}
	out := new(Seat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedWorkspace) DeepCopyInto(out *SharedWorkspace) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedWorkspace.
func (in *SharedWorkspace) DeepCopy() *SharedWorkspace {
	if in == nil {
		return nil
	}
	out := new(SharedWorkspace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Team) DeepCopyInto(out *Team) {
	*out = *in
	if in.AccessProfiles != nil {
		in, out := &in.AccessProfiles, &out.AccessProfiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InstructionRefs != nil {
		in, out := &in.InstructionRefs, &out.InstructionRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SharedMemory != nil {
		in, out := &in.SharedMemory, &out.SharedMemory
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Team.
func (in *Team) DeepCopy() *Team {
	if in == nil {
		return nil
	}
	out := new(Team)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamTemplate) DeepCopyInto(out *TeamTemplate) {
	*out = *in
	if in.InstructionRefs != nil {
		in, out := &in.InstructionRefs, &out.InstructionRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SharedMemory != nil {
		in, out := &in.SharedMemory, &out.SharedMemory
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamTemplate.
func (in *TeamTemplate) DeepCopy() *TeamTemplate {
	if in == nil {
		return nil
	}
	out := new(TeamTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolsAccess) DeepCopyInto(out *ToolsAccess) {
	*out = *in
	if in.Binaries != nil {
		in, out := &in.Binaries, &out.Binaries
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolsAccess.
func (in *ToolsAccess) DeepCopy() *ToolsAccess {
	if in == nil {
		return nil
	}
	out := new(ToolsAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkPublication) DeepCopyInto(out *WorkPublication) {
	*out = *in
	if in.Stores != nil {
		in, out := &in.Stores, &out.Stores
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkPublication.
func (in *WorkPublication) DeepCopy() *WorkPublication {
	if in == nil {
		return nil
	}
	out := new(WorkPublication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceBinding) DeepCopyInto(out *WorkspaceBinding) {
	*out = *in
	if in.Shared != nil {
		in, out := &in.Shared, &out.Shared
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceBinding.
func (in *WorkspaceBinding) DeepCopy() *WorkspaceBinding {
	if in == nil {
		return nil
	}
	out := new(WorkspaceBinding)
	in.DeepCopyInto(out)
	return out
}
