//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentOrganization) DeepCopyInto(out *AgentOrganization) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentOrganization.
func (in *AgentOrganization) DeepCopy() *AgentOrganization {
	if in == nil {
		return nil
	}
	out := new(AgentOrganization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentOrganization) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentOrganizationList) DeepCopyInto(out *AgentOrganizationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentOrganization, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentOrganizationList.
func (in *AgentOrganizationList) DeepCopy() *AgentOrganizationList {
	if in == nil {
		return nil
	}
	out := new(AgentOrganizationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentOrganizationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentOrganizationSpec) DeepCopyInto(out *AgentOrganizationSpec) {
	*out = *in
	in.OrganizationSpec.DeepCopyInto(&out.OrganizationSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentOrganizationSpec.
func (in *AgentOrganizationSpec) DeepCopy() *AgentOrganizationSpec {
	if in == nil {
		return nil
	}
	out := new(AgentOrganizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentOrganizationStatus) DeepCopyInto(out *AgentOrganizationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Seats != nil {
		in, out := &in.Seats, &out.Seats
		*out = make(map[string]SeatSummary, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ConnectionDetails != nil {
		in, out := &in.ConnectionDetails, &out.ConnectionDetails
		*out = new(ConnectionDetails)
		(*in).DeepCopyInto(*out)
	}
	if in.LastVerifiedTime != nil {
		in, out := &in.LastVerifiedTime, &out.LastVerifiedTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentOrganizationStatus.
func (in *AgentOrganizationStatus) DeepCopy() *AgentOrganizationStatus {
	if in == nil {
		return nil
	}
	out := new(AgentOrganizationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSeat) DeepCopyInto(out *AgentSeat) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSeat.
func (in *AgentSeat) DeepCopy() *AgentSeat {
	if in == nil {
		return nil
	}
	out := new(AgentSeat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentSeat) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSeatList) DeepCopyInto(out *AgentSeatList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentSeat, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSeatList.
func (in *AgentSeatList) DeepCopy() *AgentSeatList {
	if in == nil {
		return nil
	}
	out := new(AgentSeatList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentSeatList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSeatSpec) DeepCopyInto(out *AgentSeatSpec) {
	*out = *in
	in.Workspace.DeepCopyInto(&out.Workspace)
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = make([]ToolCapability, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSeatSpec.
func (in *AgentSeatSpec) DeepCopy() *AgentSeatSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSeatSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSeatStatus) DeepCopyInto(out *AgentSeatStatus) {
	*out = *in
	if in.LastActivityTime != nil {
		in, out := &in.LastActivityTime, &out.LastActivityTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Probe != nil {
		in, out := &in.Probe, &out.Probe
		*out = new(SeatProbeStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.RetiringUntil != nil {
		in, out := &in.RetiringUntil, &out.RetiringUntil
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSeatStatus.
func (in *AgentSeatStatus) DeepCopy() *AgentSeatStatus {
	if in == nil {
		return nil
	}
	out := new(AgentSeatStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionDetails) DeepCopyInto(out *ConnectionDetails) {
	*out = *in
	if in.Representatives != nil {
		in, out := &in.Representatives, &out.Representatives
		*out = make(map[string]RepresentativeEndpoint, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionDetails.
func (in *ConnectionDetails) DeepCopy() *ConnectionDetails {
	if in == nil {
		return nil
	}
	out := new(ConnectionDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepresentativeEndpoint) DeepCopyInto(out *RepresentativeEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepresentativeEndpoint.
func (in *RepresentativeEndpoint) DeepCopy() *RepresentativeEndpoint {
	if in == nil {
		return nil
	}
	out := new(RepresentativeEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeatProbeStatus) DeepCopyInto(out *SeatProbeStatus) {
	*out = *in
	if in.StartedTime != nil {
		in, out := &in.StartedTime, &out.StartedTime
		*out = (*in).DeepCopy()
	}
	if in.CompletedTime != nil {
		in, out := &in.CompletedTime, &out.CompletedTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeatProbeStatus.
func (in *SeatProbeStatus) DeepCopy() *SeatProbeStatus {
	if in == nil {
		return nil
	}
	out := new(SeatProbeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeatSummary) DeepCopyInto(out *SeatSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeatSummary.
func (in *SeatSummary) DeepCopy() *SeatSummary {
	if in == nil {
		return nil
	}
	out := new(SeatSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolCapability) DeepCopyInto(out *ToolCapability) {
	*out = *in
	if in.Operations != nil {
		in, out := &in.Operations, &out.Operations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolCapability.
func (in *ToolCapability) DeepCopy() *ToolCapability {
	if in == nil {
		return nil
	}
	out := new(ToolCapability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceRef) DeepCopyInto(out *WorkspaceRef) {
	*out = *in
	if in.Shared != nil {
		in, out := &in.Shared, &out.Shared
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceRef.
func (in *WorkspaceRef) DeepCopy() *WorkspaceRef {
	if in == nil {
		return nil
	}
	out := new(WorkspaceRef)
	in.DeepCopyInto(out)
	return out
}
